using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace LeMaiDomain
{
	[Serializable()]
	public class GsRequestFindProduct
	{
		//Khai bao các biến
		public System.String Id { get; set; }
		public System.String RequestCode { get; set; }
		public System.String ProductName { get; set; }
		public System.String ProductNameUnsign { get; set; }
		public System.String RequestImage { get; set; }
		public System.DateTime BeginRequestDate { get; set; }
		public System.String FK_InventoryCategory { get; set; }
		public System.String Fk_Provine { get; set; }
		public System.String DeliveryAddress { get; set; }
		public System.String Description { get; set; }
		public System.Int32 Quantity { get; set; }
		public System.String Fk_Unit { get; set; }
		public System.String Packing { get; set; }
		public System.Decimal QuantityOfPacking { get; set; }
		public System.Int32 WarrantyMonth { get; set; }
		public System.String TradeMark { get; set; }
		public System.String DesignTradeMarkFile { get; set; }
		public System.String AdditionalLabel { get; set; }
		public System.DateTime EndRequestDate { get; set; }
		public System.String RequestNote { get; set; }
		public System.Boolean IsCustomerRequest { get; set; }
		public System.String Fk_UserSaleRequest { get; set; }
		public System.Int32? HeightX { get; set; }
		public System.Int32? WidthY { get; set; }
		public System.Int32? ThicknessZ { get; set; }
		public System.Decimal? Weight { get; set; }
		public System.String Fk_WeightUnit { get; set; }
		public System.Int32 Fk_Status { get; set; }
		public System.String Fk_UserRequestApprover { get; set; }
		public System.DateTime? UserRequestApproverDate { get; set; }
		public System.String RequestApproverNote { get; set; }
		public System.String Fk_UserSourceProcess { get; set; }
		public System.DateTime? SourceProcessDate { get; set; }
		public System.String Fk_UserSourceApprover { get; set; }
		public System.DateTime? SourceApproverDate { get; set; }
		public System.String SourceApproverNote { get; set; }
		public System.String Fk_UserSourceEstimator { get; set; }
		public System.DateTime? SourceEstimator { get; set; }
		public System.String SourceEstimatorNote { get; set; }
		public System.Boolean IsLCOFDone { get; set; }
		public System.String Fk_UserLCOFProcess { get; set; }
		public System.DateTime? LCOFDate { get; set; }
		public System.Boolean IsCustomsDone { get; set; }
		public System.String Fk_UserCustomsProcess { get; set; }
		public System.DateTime? CustomsProcessDate { get; set; }
		public System.Boolean IsTruckingDone { get; set; }
		public System.String Fk_UserTruckingProcess { get; set; }
		public System.DateTime? TruckingProcessDate { get; set; }
		public System.String Fk_OPApprover { get; set; }
		public System.DateTime? OPApproverDate { get; set; }
		public System.String OPApproverNote { get; set; }
		public System.Boolean IsApproverLCOF { get; set; }
		public System.Boolean IsApproverCustoms { get; set; }
		public System.Boolean IsApproverTrucking { get; set; }
		public System.String Fk_OPEstimator { get; set; }
		public System.DateTime? OPEstimatorDate { get; set; }
		public System.String OPEstimatorNote { get; set; }
		public System.Boolean IsEstimatorLCOF { get; set; }
		public System.Boolean IsEstimatorCustoms { get; set; }
		public System.Boolean IsEstimatorTrucking { get; set; }
		public System.Decimal DemoTransferCost { get; set; }
		public System.Decimal DemoCost { get; set; }
		public System.Decimal MoqTransferCost { get; set; }
		public System.Decimal MoqCost { get; set; }
		public System.Decimal DC20TransferCost { get; set; }
		public System.Decimal DC20Cost { get; set; }
		public System.Decimal DC40TransferCost { get; set; }
		public System.Decimal DC40Cost { get; set; }
		public System.Decimal DC40HTransferCost { get; set; }
		public System.Decimal DC40HCost { get; set; }
		public System.Decimal DemoWholesaleCost { get; set; }
		public System.Decimal MoqWholesaleCost { get; set; }
		public System.Decimal DC20WholesaleCost { get; set; }
		public System.Decimal DC40WholesaleCost { get; set; }
		public System.Decimal DC40HWholesaleCost { get; set; }
		public System.Decimal DemoRetailCost { get; set; }
		public System.Decimal MoqRetailCost { get; set; }
		public System.Decimal DC20RetailCost { get; set; }
		public System.Decimal DC40RetailCost { get; set; }
		public System.Decimal DC40HRetailCost { get; set; }
		public System.Int32 DemoWholesalePercent { get; set; }
		public System.Int32 MoqWholesalePercent { get; set; }
		public System.Int32 DC20WholesalePercent { get; set; }
		public System.Int32 DC40WholesalePercent { get; set; }
		public System.Int32 DC40HWholesalePercent { get; set; }
		public System.Int32 DemoRetailPercent { get; set; }
		public System.Int32 MoqRetailPercent { get; set; }
		public System.Int32 DC20RetailPercent { get; set; }
		public System.Int32 DC40RetailPercent { get; set; }
		public System.Int32 DC40HRetailPercent { get; set; }
		public System.Decimal DemoWholesalePrice { get; set; }
		public System.Decimal MoqWholesalePrice { get; set; }
		public System.Decimal DC20WholesalePrice { get; set; }
		public System.Decimal DC40WholesalePrice { get; set; }
		public System.Decimal DC40HWholesalePrice { get; set; }
		public System.Decimal DemoRetailPrice { get; set; }
		public System.Decimal MoqRetailPrice { get; set; }
		public System.Decimal DC20RetailPrice { get; set; }
		public System.Decimal DC40RetailPrice { get; set; }
		public System.Decimal DC40HRetailPrice { get; set; }
		public System.String Fk_FinishEstimator { get; set; }
		public System.DateTime FinishEstimatorDate { get; set; }
		public System.String Fk_InventoryItem { get; set; }
		public System.String ReferRequestFindProduct { get; set; }
		public System.Int32 IsDelete { get; set; }
		public System.Int32 FK_TypeOfRequest { get; set; }
		public System.Boolean IsBorderTradeDemo { get; set; }
		public System.Decimal DemoShippingPrice { get; set; }
		public System.Boolean IsBorderTradeMoq { get; set; }
		public System.Decimal MoqShippingPrice { get; set; }
		public System.Boolean IsSkipAllStep { get; set; }
		public System.String WeightFrom { get; set; }
		public System.String WeightTo { get; set; }
		public System.Boolean IsNetWeight { get; set; }
		public System.Decimal WishPrice { get; set; }
		public System.String FK_UnitPacking { get; set; }
		public System.Boolean IsReceptionLCOF { get; set; }
		public System.Boolean IsReceptionCustoms { get; set; }
		public System.Boolean IsReceptionTrucking { get; set; }
		public System.Int32 FK_RequestPrioty { get; set; }
		public System.String PriotyName { get; set; }
		public System.String ExportRequestTypeName { get; set; }
		public System.Boolean IsDC20Price { get; set; }
		public System.Boolean IsDC40Price { get; set; }
		public System.Boolean IsDC40HPrice { get; set; }
		public System.String UserCustomsProcess { get; set; }
		public System.String UserLCOFProcess { get; set; }
		public System.String UserTruckingProcess { get; set; }
		public System.String UserRequestApprover { get; set; }
		public System.String UserSourceApprover { get; set; }
		public System.String UserSourceEstimator { get; set; }
		public System.String UserSourceProcess { get; set; }
		public GsRequestFindProduct(){}
	}
}
